server:
  port: ${SERVER_PORT:8888}

spring:
  application:
    name: iv-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: ${RUTA_CONFIG:/config}
    encrypt:
      enabled: false

  security:
    user:
      name: ${CONFIG_SERVER_USERNAME:iv-admin}
      password: ${CONFIG_SERVER_PASSWORD:iv-admin}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

encrypt:
  key: ${ENCRYPT_KEY:}