server:
  port: 8888

spring:
  application:
    name: iv-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: ${RUTA_CONFIG}
    encrypt:
      enabled: false
  
  security:
    user:
      name: iv-admin
      password: iv-admin

eureka:
  client:
    # Cambia estos dos a 'true'
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

encrypt:
  key: ${ENCRYPT_KEY}

security:
  rsa:
    private-key-path: file:D:/claves/k/private_key.pem