spring:
  application:
    name: iv-jpa-destinos
  datasource:
    url: jdbc:postgresql://localhost:5432/rhviajesBD
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
 
#Tomcat Embedded Server Configuration
server: 
  port: 0


#Eureka Configuration Properties  
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
