spring:
  application:
    name: iv-service-viajes
 
#Tomcat Embedded Server Configuration
server: 
  port: 24209
  
  servlet:
    context-path: /iv-service-viajes
 
#Eureka Configuration Properties  
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka