info:
 component: iv-gateway

spring:
  application:
    name: iv-gateway
    
server:
  port: 7000

  
zuul:
  routes:
    serv-jpa-destinos:
        path: /iv-jpa-destinos/**
        serviceId: iv-jpa-destinos
    serv-neg-viajes:
        path: /iv-service-viajes/**
        serviceId: iv-service-viajes
 
#Eureka Configuration Properties
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
